force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>An internal announcement of updates, important information, and notifications</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Announcement__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Announcement__c/fields/Highlights__c.field-meta.xml
<CustomField>
    <fullName>Highlights__c</fullName>
    <description>Key takeaways for this announcement</description>
    <inlineHelpText>Key takeaways for this announcement</inlineHelpText>
    <label>Highlights</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Announcement__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this announcement will remain at the top of bulletin boards</description>
    <inlineHelpText>If checked, this announcement will remain at the top of bulletin boards</inlineHelpText>
    <label>Priority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Announcement__c/fields/Priority_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Priority_End_Date_Time__c</fullName>
    <description>If set, the priority flag will be ignored after this date/time has passed</description>
    <inlineHelpText>If set, the priority flag will be ignored after this date/time has passed</inlineHelpText>
    <label>Priority End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <description>Topics are the primary tool for categorizing Tickets, Articles, and Announcements. A Topic can be a theme, concept, activity, or business area.</description>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/fields/Hex_Color__c.field-meta.xml
<CustomField>
    <fullName>Hex_Color__c</fullName>
    <description>The hexadecimal color value to associate with this topic</description>
    <inlineHelpText>The hexadecimal color value to associate with this topic</inlineHelpText>
    <label>Hex Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Topic_Tag__c/Topic_Tag__c.object-meta.xml
<CustomObject>
    <description>Junction object to tag topics for Articles, Tickets, and Announcements</description>
    <label>Topic Tag</label>
    <nameField>
        <displayFormat>Tag-{00000}</displayFormat>
        <label>Topic Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Topic Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic_Tag__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Announcement</label>
    <referenceTo>Announcement__c</referenceTo>
    <relationshipLabel>Topic Tags</relationshipLabel>
    <relationshipName>Topic_Tags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Topic_Tag__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Topic Tags</relationshipLabel>
    <relationshipName>Topic_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AnnouncementBoardController.cls
public with sharing class AnnouncementBoardController {

    @AuraEnabled(cacheable=true)
    public static List<Announcement__c> getAnnouncements(){
        try {
            return [
                SELECT Id, Name, Highlights__c, Details__c, Priority__c, Priority_End_Date_Time__c, 
                       (SELECT Id, Topic__c, Topic__r.Hex_Color__c FROM Topic_Tags__r)
                  FROM Announcement__c
                 ORDER BY Priority__c DESC, CreatedDate DESC
                 LIMIT 20
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}