force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>An internal announcement of updates, important information, and notifications</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Announcement_Notification__e/Announcement_Notification__e.object-meta.xml
<CustomObject>
    <description>Notifies announcement boards of updates and triggers a data refresh</description>
    <label>Announcement Notification</label>
    <pluralLabel>Announcement Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Announcement_Notification__e/fields/DML_Type__c.field-meta.xml
<CustomField>
    <fullName>DML_Type__c</fullName>
    <description>The type of database event that occurred (insert/update/delete/undelete)</description>
    <label>DML Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Announcement_Notification__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The record id of the inserted or updated record</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnnouncementNotificationService.cls
public class AnnouncementNotificationService {

    public void notifyComponents(
        List<Announcement__c> lstAnnouncements
    ) {
        System.debug('::::::: entered AnnouncementNotificationService.notifyComponents');
        List<Announcement_Notification__e> lstNotifications = new List<Announcement_Notification__e>();
        String strDmlType = getDmlType();
        for (Announcement__c ann : lstAnnouncements) {
            System.debug('::::::: adding notification for announcement id ' + ann.Id);
            lstNotifications.add(
                new Announcement_Notification__e(
                    Record_Id__c = ann.Id,
                    DML_Type__c = strDmlType
                )
            );
        }
        System.debug('::::::: number of notifications to publish: ' + lstNotifications.size());
        EventBus.publish(lstNotifications);
    }
    
    private String getDmlType() {
        System.debug('::::::: entered AnnouncementNotificationService.getDmlType');
        String strDmlType = '';
        switch on Trigger.operationType {
            when BEFORE_INSERT, AFTER_INSERT {
                strDmlType = 'Insert';
            }
            when BEFORE_UPDATE, AFTER_UPDATE {
                strDmlType = 'Update';
            }
        }
        System.debug('::::::: dml type is ' + strDmlType);
        return strDmlType;
    }

}