force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Represents a request, issue, or work order</description>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bug/Issue</fullName>
            </value>
            <value>
                <fullName>Enhancement Request</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>General Inquiry</fullName>
            </value>
            <value>
                <fullName>How To</fullName>
            </value>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Merge Request</fullName>
            </value>
            <value>
                <fullName>Physical Error</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Project Request</fullName>
                <isActive>false</isActive>
                <label>Project Request</label>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Repair Request</fullName>
                <isActive>false</isActive>
                <label>Repair Request</label>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Software Error</fullName>
                <isActive>false</isActive>
                <label>Software Error</label>
            </value>
            <value>
                <fullName>Staff Updates</fullName>
            </value>
            <value>
                <fullName>System Access</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/recordTypes/Engineering.recordType-meta.xml
<RecordType>
    <fullName>Engineering</fullName>
    <active>true</active>
    <description>Repairs, maintenance, and work orders</description>
    <label>Engineering</label>
</RecordType>

force-app/main/default/classes/TicketTrigger_Test.cls
/********************************************
 * All actions fired by TicketTrigger are flows. These tests
 * attempt only to make the ticket trigger fire successfully
 ********************************************/
@isTest
private class TicketTrigger_Test {

    private static Id engineeringRecordTypeId = Schema.SObjectType.Ticket__c.getRecordTypeInfosByDeveloperName().get('Engineering').getRecordTypeId();

    @isTest
    static void testTicketTriggerOnInsert() {
        Id engineeringRecordTypeId = Schema.SObjectType.Ticket__c.getRecordTypeInfosByDeveloperName().get('Engineering').getRecordTypeId();
        
        Ticket__c tik = getTicket();

        Test.startTest();
        Database.SaveResult sr = Database.insert(tik, false);
        Test.stopTest();

        System.assert(sr.isSuccess(), 'Ticket should have successfully saved');
    }

    @isTest
    static void testTicketTriggerBatch() {
        List<Ticket__c> lstTickets = new List<Ticket__c>();
        for (Integer i = 0; i < 201; i++) {
            lstTickets.add(
                getTicket()
            );
        }

        Test.startTest();
        List<Database.SaveResult> lstSRs = Database.insert(lstTickets, false);
        Test.stopTest();

        for (Database.SaveResult sr : lstSRs) {
            System.assert(sr.isSuccess(), 'Ticket should have successfully saved');
        }
    }

    private static Ticket__c getTicket() {
        Ticket__c tik = new Ticket__c();
        tik.Subject__c = 'Testing tickets';
        tik.Description__c = 'Good news folks. It works.';
        tik.Status__c = 'Assigned';
        tik.OwnerId = UserInfo.getUserId();
        tik.Priority__c = 'Low';
        tik.Type__c = 'General Inquiry';
        tik.RecordTypeId = engineeringRecordTypeId;
        return tik;
    }
    
}