force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Represents a request, issue, or work order</description>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Date_Time_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Opened__c</fullName>
    <label>Date/Time Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Parent_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Child Tickets</relationshipLabel>
    <relationshipName>Child_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ultimate_Parent_ID__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_ID__c</fullName>
    <description>The ID of the ticket at the top of this ticket&apos;s hierarchy</description>
    <formula>IF( ISBLANK( Parent_Ticket__c ),
 Id,
 IF( ISBLANK( Parent_Ticket__r.Parent_Ticket__c ),
  Parent_Ticket__c,
  Parent_Ticket__r.Parent_Ticket__c
 )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The ID of the ticket at the top of this ticket&apos;s hierarchy</inlineHelpText>
    <label>Ultimate Parent ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TicketHierarchyModelController.cls
public with sharing class TicketHierarchyModelController {

    @AuraEnabled(cacheable=true)
    public static List<Ticket__c> getTicketsInHierarchy(
        String ultimateParentId
    ) {
        try {
            return [
                SELECT Id, 
                       Name, 
                       Parent_Ticket__c, 
                       Ultimate_Parent_ID__c, 
                       OwnerId, 
                       Owner.Name, 
                       Status__c, 
                       Subject__c, 
                       Date_Time_Opened__c
                  FROM Ticket__c
                 WHERE Ultimate_Parent_ID__c = :ultimateParentId
                 ORDER BY Name ASC
                 LIMIT 10000
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}